# Generated by Django 6.1 on 2026-08-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_name',
            field=models.CharField(blank=True, help_text="Name to engrave, e.g. 'H.J. Zala'", max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_subtitle',
            field=models.CharField(blank=True, help_text="Designation/department, e.g. 'P.S.I'", max_length=100),
        ),
    ]
