# Generated by Django 6.1 on 2026-09-01 08:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_custom_name_orderitem_custom_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_screenshot'),
        ),
    ]
